[package]
name = "hive"
version = "0.1.0"
authors = ["Anyere Bendrien <anyere.bendrien@posteo.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
